-- EMS V1 production schema. Run once in a new Supabase project's SQL Editor.
-- No demo/seed records are intentionally included.
create extension if not exists pgcrypto;

create type public.store_status as enum ('active','inactive');
create type public.license_status as enum ('pending','active','expired','rejected');
create type public.payment_method as enum ('cash','bank','bkash','nagad','other');
create type public.attendance_status as enum ('present','absent');

create table public.administrators (
 id uuid primary key default gen_random_uuid(), name text not null check (char_length(name) between 2 and 120), address text, phone text not null, email text not null unique check (email = lower(email)), password_hash text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.stores (
 id uuid primary key default gen_random_uuid(), admin_id uuid not null references public.administrators(id) on delete restrict,
 name text not null, address text, phone text not null, phone2 text, email text, website text, status public.store_status not null default 'inactive', low_stock_threshold numeric(14,3) not null default 5 check(low_stock_threshold >= 0), created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.licenses (
 id uuid primary key default gen_random_uuid(), store_id uuid not null references public.stores(id) on delete cascade, duration_months integer not null check(duration_months in (6,12,18,24)), amount numeric(12,2) not null check(amount in (500,800,1200,1500)), payment_method public.payment_method not null check(payment_method in ('bkash','nagad')), payment_number text not null, transaction_id text not null, status public.license_status not null default 'pending', starts_at timestamptz, expires_at timestamptz, reviewed_at timestamptz, reviewed_by uuid references public.administrators(id), review_note text, created_at timestamptz not null default now(), unique(payment_method, transaction_id)
);
create table public.staff (
 id uuid primary key default gen_random_uuid(), store_id uuid not null references public.stores(id) on delete cascade, full_name text not null, position text, phone text not null, email text, user_id text not null, password_hash text not null, basic_salary numeric(12,2) not null default 0 check(basic_salary >= 0), active boolean not null default true, permissions jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(store_id,user_id)
);
create table public.suppliers (id uuid primary key default gen_random_uuid(), store_id uuid not null references public.stores(id) on delete cascade, name text not null, address text, phone text not null, phone2 text, email text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.customers (id uuid primary key default gen_random_uuid(), store_id uuid not null references public.stores(id) on delete cascade, name text not null, address text, phone text not null, phone2 text, email text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.inventory_items (id uuid primary key default gen_random_uuid(), store_id uuid not null references public.stores(id) on delete cascade, item_code text not null, description text not null, unit text not null, sale_price numeric(14,2) not null default 0 check(sale_price >= 0), total_stock numeric(14,3) not null default 0, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(store_id,item_code));
create table public.invoices (id uuid primary key default gen_random_uuid(), store_id uuid not null references public.stores(id) on delete cascade, kind text not null check(kind in ('purchase','sale')), invoice_number text not null, party_id uuid, invoice_date date not null, payment_method public.payment_method not null default 'cash', transaction_id text, notes text, subtotal numeric(14,2) not null default 0, tax_percent numeric(7,3) not null default 0, discount numeric(14,2) not null default 0, tax_amount numeric(14,2) not null default 0, paid_amount numeric(14,2) not null default 0, total_due numeric(14,2) not null default 0, created_by uuid, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(store_id,invoice_number));
create table public.invoice_lines (id uuid primary key default gen_random_uuid(), invoice_id uuid not null references public.invoices(id) on delete cascade, item_id uuid not null references public.inventory_items(id) on delete restrict, quantity numeric(14,3) not null check(quantity > 0), unit_price numeric(14,2) not null check(unit_price >= 0), line_total numeric(14,2) not null check(line_total >= 0));
create table public.expenses (id uuid primary key default gen_random_uuid(), store_id uuid not null references public.stores(id) on delete cascade, expense_date date not null, details text not null, total numeric(14,2) not null check(total>=0), paid numeric(14,2) not null default 0 check(paid>=0), due numeric(14,2) generated always as (total-paid) stored, note text, created_by uuid, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.attendance (id uuid primary key default gen_random_uuid(), store_id uuid not null references public.stores(id) on delete cascade, staff_id uuid not null references public.staff(id) on delete cascade, attendance_date date not null default current_date, status public.attendance_status not null, note text, recorded_by uuid, created_at timestamptz not null default now(), unique(staff_id,attendance_date));
create table public.device_logins (id uuid primary key default gen_random_uuid(), store_id uuid not null references public.stores(id) on delete cascade, staff_id uuid references public.staff(id) on delete set null, device_fingerprint text not null, user_agent text, last_seen_at timestamptz not null default now(), unique(store_id,device_fingerprint));
create table public.activity_logs (id bigint generated always as identity primary key, store_id uuid references public.stores(id) on delete cascade, actor_type text not null, actor_id uuid, action text not null, entity_type text, entity_id text, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table public.error_logs (id bigint generated always as identity primary key, store_id uuid references public.stores(id) on delete cascade, actor_id uuid, message text not null, context jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());

create index on public.stores(admin_id); create index on public.staff(store_id); create index on public.inventory_items(store_id); create index on public.invoices(store_id,kind,invoice_date desc); create index on public.activity_logs(store_id,created_at desc);

-- Service-role API is the only database client. Revoke public direct data access.
revoke all on all tables in schema public from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;
alter table public.administrators enable row level security; alter table public.stores enable row level security; alter table public.licenses enable row level security; alter table public.staff enable row level security; alter table public.suppliers enable row level security; alter table public.customers enable row level security; alter table public.inventory_items enable row level security; alter table public.invoices enable row level security; alter table public.invoice_lines enable row level security; alter table public.expenses enable row level security; alter table public.attendance enable row level security; alter table public.device_logins enable row level security; alter table public.activity_logs enable row level security; alter table public.error_logs enable row level security;
